version: "3.9"
   
services:
  web:
    build: .
    command: bash -c "cd server; gunicorn api.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:8000:8000"
    # CAREFUL: this checks to see migrations have started, not necessarily finished
    depends_on:
      - migrate

  migrate:
    build: .
    entrypoint: python server/manage.py migrate
    healthcheck:
      test: "exit 0"
    volumes:
      - .:/code

