version: "3.3"
   
services:
  web:
    build: .
    command: python server/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  migrate:
    build: .
    entrypoint: python server/manage.py migrate
    healthcheck:
      test: "exit 0"
    volumes:
      - .:/code

