version: "3.9"
   
services:
  web:
    build: .
    command: bash -c "cd server; gunicorn api.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # CAREFUL: this checks to see migrations have started, not necessarily finished
    depends_on:
      - migrate

  migrate:
    build: .
    entrypoint: python server/manage.py migrate
    healthcheck:
      test: "exit 0"
    volumes:
      - .:/code

  selenium:
    image: selenium/standalone-chrome:97.0-chromedriver-97.0

    ports:
      - "4444:4444"
    restart: always

  scraper:
    build:
      context: .
    volumes:
      - .:/code
    command: python server/scraper.py
    depends_on:
      - selenium

